name: qas

dep:
  ops:
    type: git
    url: "https://github.com/hatlonely/ops.git"
    version: master

env:
  default:
  dev:
    IMM_AK: {{.credential.imm.accessKeyId}}
    IMM_SK: {{.credential.imm.accessKeySecret}}
    IMM_ENDPOINT: https://imm.cn-shanghai.aliyuncs.com
    OTS_AK: {{.credential.ots.accessKeyId}}
    OTS_SK: {{.credential.ots.accessKeySecret}}
    OTS_INSTANCE: imm-dev-hl
    OTS_ENDPOINT: https://imm-dev-hl.cn-shanghai.ots.aliyuncs.com

task:
  sample-recommend:
    step:
      - sh ${DEP}/ops/tool/render.sh ops/sample-recommend ${TMP}/sample-recommend
      - python3 main.py --test "${TMP}/sample-recommend"
  sample-simple:
    step:
      - sh ${DEP}/ops/tool/render.sh ops/sample-simple ${TMP}/sample-simple
      - python3 main.py --test "${TMP}/sample-simple"
  install:
    step:
      - python3 setup.py install

