name: qas

dep:
  ops:
    type: git
    url: "https://github.com/hatlonely/ops.git"
    version: master

env:
  default:
  dev:
    POP_AK: {{.credential.pop.accessKeyId}}
    POP_SK: {{.credential.pop.accessKeySecret}}
    OTS_AK: {{.credential.ots.accessKeyId}}
    OTS_SK: {{.credential.ots.accessKeySecret}}
    POP_ENDPOINT: https://imm.cn-shanghai.aliyuncs.com
    OTS_INSTANCE: hatlonely-ots-sh
    OTS_ENDPOINT: https://hatlonely-ots-sh.cn-shanghai.ots.aliyuncs.com

task:
  sample-recommend:
    step:
      - sh ${DEP}/ops/tool/render.sh ops/sample-recommend ${TMP}/sample-recommend
      - qas --test "${TMP}/sample-recommend"
  sample-simple:
    step:
      - qas --test ops/sample-simple/sample.yaml
  install:
    step:
      - python3 setup.py install

