name: qas

env:
  default:
    NAME: qas
    REGISTRY_ENDPOINT: "{{.registry.dockerhub.endpoint}}"
    REGISTRY_USERNAME: "{{.registry.dockerhub.username}}"
    REGISTRY_PASSWORD: "{{.registry.dockerhub.password}}"
    REGISTRY_NAMESPACE: "{{.registry.dockerhub.namespace}}"
    IMAGE_TAG: "$(git describe --tags | awk '{print(substr($0,2,length($0)))}'; test ${PIPESTATUS[0]} -eq 0)"

task:
  self-test:
    step:
      - qas -t ops/self-test --parallel --reporter html > self-test.html
  install:
    step:
      - python3 setup.py install
  image:
    step:
      - docker login --username="${REGISTRY_USERNAME}" --password="${REGISTRY_PASSWORD}" "${REGISTRY_ENDPOINT}"
      - docker build --tag=${REGISTRY_ENDPOINT}/${REGISTRY_NAMESPACE}/${NAME}:${IMAGE_TAG} .
      - docker push "${REGISTRY_ENDPOINT}/${REGISTRY_NAMESPACE}/${NAME}:${IMAGE_TAG}"
  pip:
    step:
      - rm -rf dist
      - python3 setup.py sdist
      - pip3 install twine
      - twine upload dist/*
