name: qas

dep:
  ops:
    type: git
    url: "https://github.com/hatlonely/ops.git"
    version: master

env:
  default:
  dev:
    IMM_AK: {{.credential.imm.accessKeyId}}
    IMM_SK: {{.credential.imm.accessKeySecret}}
    IMM_ENDPOINT: https://imm.cn-shanghai.aliyuncs.com
    OTS_AK: {{.credential.ots.accessKeyId}}
    OTS_SK: {{.credential.ots.accessKeySecret}}
    OTS_INSTANCE: imm-dev-hl
    OTS_ENDPOINT: https://imm-dev-hl.cn-shanghai.ots.aliyuncs.com
    OSS_AK: {{.credential.oss.accessKeyId}}
    OSS_SK: {{.credential.oss.accessKeySecret}}
    OSS_ENDPOINT: oss-cn-shanghai.aliyuncs.com
    OSS_BUCKET: imm-test-hl-shanghai
    MNS_AK: {{.credential.mns.accessKeyId}}
    MNS_SK: {{.credential.mns.accessKeySecret}}
    MNS_ENDPOINT: http://{{.credential.mns.ownerId}}.mns.cn-shanghai.aliyuncs.com

task:
  example-docs:
    args:
      case:
        type: string
    step:
      - sh ${DEP}/ops/tool/render.sh ops/example-docs ${TMP}/example-docs
      - |
        if [[ "${case}" == "" ]]; then
          python3 main.py --test "${TMP}/example-docs"
        else
          python3 main.py --test "${TMP}/example-docs" --case "${case}"
        fi
  install:
    step:
      - python3 setup.py install
