name: TestLocal
step:
  - ctx: shell
    req:
      command: qas --test ops/example-docs/local --reporter json
      decoder: json
    res:
      exitCode: 0
      json: {
        "#id": "len(val) > 0",
        "directory": "ops/example-docs/local",
        "name": "local-example",
        "status": "pass",
        "description": "",
        "isSkip": false,
        "isPass": true,
        "isErr": false,
        "err": "",
        "#elapse": "val > 0",
        "casePass": 1,
        "caseFail": 0,
        "caseSkip": 0,
        "setUpPass": 0,
        "setUpFail": 0,
        "tearDownPass": 0,
        "tearDownFail": 0,
        "currCasePass": 1,
        "currCaseFail": 0,
        "currCaseSkip": 0,
        "stepPass": 1,
        "stepFail": 0,
        "stepSkip": 0,
        "assertionPass": 2,
        "assertionFail": 0,
        "subTestPass": 0,
        "subTestSkip": 0,
        "subTestFail": 0,
        "cases": [
          {
            "id": "ctx",
            "name": "LocalExample",
            "directory": "ops/example-docs/local",
            "description": "",
            "command": "qas -t \"ops/example-docs/local\" -c \"\" --case-id \"ctx\"",
            "status": "pass",
            "#elapse": "val > 0",
            "isPass": true,
            "isSkip": false,
            "steps": [
              {
                "name": "echo",
                "description": "",
                "ctx": "shell",
                "isSkip": false,
                "isPass": true,
                "req": {
                  "command": "echo -n hello world",
                  "env": {
                    "KEY1": "world",
                    "KEY2": "hello"
                  },
                  "envs": {},
                  "decoder": "text",
                  "files": {},
                  "tmp": "/tmp",
                  "clean": true
                },
                "res": {
                  "exitCode": 0,
                  "stdout": "hello world",
                  "stderr": ""
                },
                "subSteps": [
                  {
                    "isPass": true,
                    "isErr": false,
                    "err": "",
                    "req": {
                      "command": "echo -n hello world",
                      "env": {
                        "KEY1": "world",
                        "KEY2": "hello"
                      },
                      "envs": {},
                      "decoder": "text",
                      "files": {},
                      "tmp": "/tmp",
                      "clean": true
                    },
                    "res": {
                      "exitCode": 0,
                      "stdout": "hello world",
                      "stderr": ""
                    },
                    "assertions": [
                      {
                        "isPass": true,
                        "message": "OK",
                        "node": "exitCode",
                        "val": 0,
                        "expect": 0
                      },
                      {
                        "isPass": true,
                        "message": "OK",
                        "node": "stdout",
                        "val": "hello world",
                        "expect": "hello world"
                      }
                    ],
                    "assertionPass": 2,
                    "assertionFail": 0,
                    "#elapse": "val > 0"
                  }
                ],
                "assertionPass": 2,
                "assertionFail": 0,
                "#elapse": "val > 0"
              }
            ],
            "beforeCaseSteps": [],
            "afterCaseSteps": [],
            "stepPass": 1,
            "stepFail": 0,
            "assertionPass": 2,
            "assertionFail": 0
          }
        ],
        "setUps": [],
        "tearDowns": [],
        "subTests": []
      }
